Demo.Identity.Dapper/Entities/Identities.cs
using AspNetCore.Identity.Dapper;
using AspNetCore.Identity.Dapper.Entities;
using Dapper.Contrib.Extensions;

namespace Demo.Identity.Dapper.Entities
{
    [Table(IdentityDapperTables.DbTable.Users)]
    public class ApplicationUser : IdentityUserDapper<int>
    {
        [Key]
        public override int Id { get; set; }

        public string Image { get; set; }
        [Write(false)] public string Password { get; set; }
        [Write(false)] public bool IsAdministrator { get; set; }
    }

    [Table(IdentityDapperTables.DbTable.UserRoles)]
    public class ApplicationUserRole : IdentityUserRoleDapper<int>
    {
    }

    [Table(IdentityDapperTables.DbTable.UserClaims)]
    public class ApplicationUserClaim : IdentityUserClaimDapper<int>
    {
    }

    [Table(IdentityDapperTables.DbTable.UserLogins)]
    public class ApplicationUserLogin : IdentityUserLoginDapper<int>
    {
    }

    [Table(IdentityDapperTables.DbTable.UserTokens)]
    public class ApplicationUserToken : IdentityUserTokenDapper<int>
    {
    }

    [Table(IdentityDapperTables.DbTable.Roles)]
    public class ApplicationRole : IdentityRoleDapper<int>
    {
        [Key]
        public override int Id { get; set; }
    }

    [Table(IdentityDapperTables.DbTable.RoleClaims)]
    public class ApplicationRoleClaim : IdentityRoleClaimDapper<int>
    {
    }
}

Demo.Identity.Dapper/Models/ErrorViewModel.cs
using System;

namespace Demo.Identity.Dapper.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo.Identity.Dapper/Controllers/AuthenticateController.cs
using System.Threading.Tasks;
using Demo.Identity.Dapper.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Identity.Dapper.Controllers
{
    public class AuthenticateController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AuthenticateController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager, RoleManager<ApplicationRole> roleManager,
            IHttpContextAccessor httpContextAccessor)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(ApplicationUser model)
        {
            if (!ModelState.IsValid)
                return View();

            model.Image = "This is test custom property that got insert up to database!";
            var result = await _userManager.CreateAsync(model, model.Password);
            if (result.Succeeded)
            {
                if (!await _roleManager.RoleExistsAsync("SuperAdmin"))
                    await _roleManager.CreateAsync(new ApplicationRole(){ Name = "SuperAdmin" });
                if (!await _roleManager.RoleExistsAsync("Guest"))
                    await _roleManager.CreateAsync(new ApplicationRole() { Name = "Guest" });

                if (model.IsAdministrator)
                    await _userManager.AddToRoleAsync(model, "SuperAdmin");
                else
                    await _userManager.AddToRoleAsync(model, "Guest");

                await _signInManager.SignInAsync(model, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.Code, error.Description);
                }
            }

            return View();
        }

        public async Task<IActionResult> Login()
        {
            // Clear the existing external cookie to ensure a clean login process
            await _httpContextAccessor.HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(ApplicationUser model)
        {
            if (!ModelState.IsValid) return View();

            var result = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, false, false);
            if (result.Succeeded)
                return RedirectToAction("Index", "Home");
            if (result.RequiresTwoFactor)
            {
                ModelState.AddModelError(string.Empty, "Required 2 Factor Authenticated!");
                return View();
            }
            if (result.IsLockedOut)
            {
                ModelState.AddModelError(string.Empty, "This user is looked out!");
                return View();
            }

            ModelState.AddModelError(string.Empty, "UserName or Password is not correct!");
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            _httpContextAccessor.HttpContext.Session.Clear();
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

Demo.Identity.Dapper/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Demo.Identity.Dapper.Models;

namespace Demo.Identity.Dapper.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo.Identity.Dapper/Views/Authenticate/Login.cshtml
@model Demo.Identity.Dapper.Entities.ApplicationUser
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <h4>Login.</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

Demo.Identity.Dapper/Views/Authenticate/Register.cshtml
@model Demo.Identity.Dapper.Entities.ApplicationUser

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <h4>Create new account.</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="IsAdministrator" type="checkbox" /> Is Administrator
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

Demo.Identity.Dapper/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo.Identity.Dapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.Identity.Dapper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.Identity.Dapper</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Authenticate" asp-action="Logout">Sign Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Authenticate" asp-action="Login">Sign In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Authenticate" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Demo.Identity.Dapper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>